### ISSUE TITLE
Embed/transclusion has partial left margin

### ISSUE THREAD

**Issue by DutchPete** [nikbrunner/obsidian-deep-work-theme#18]
**Describe the bug**
An embed/transclusion in Preview shows a partial sidebar in accent color. It should not be there.
The screenshots explain what I mean.

**To Reproduce**

**Expected behavior**

**Screenshots**
Embed in Edit (Live Preview)
![image](https://user-images.githubusercontent.com/10794265/144799247-0d485105-7b3b-4237-b80e-42f2d11af2ef.png)

Same embed in Preview:
![image](https://user-images.githubusercontent.com/10794265/144799322-f52f2536-0a3c-4814-8623-025269070d1a.png)

The blue bit on the left should not be there.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.14.6

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nikbrunner** [comment]
I will check on it tonight. Thank you for reporting

**Comment by DutchPete** [comment]
Thanks for your time and a nice theme: simple and attractive without a plethora of colors.

**Comment by nikbrunner** [comment]
I couldn't reproduce this until now. Is it possible that the your file which you want to embed is empty?

**Comment by DutchPete** [comment]
Hi Nik, this is the part in your theme that causes the issue:
```css
body
  .markdown-preview-view
  .markdown-embed
  .markdown-preview-view {
  padding-left: 1.5rem;
  padding-right: 1.5rem;
  border-left: 10px solid var(--text-accent);
  border-radius: 4px;
  background: var(--background-secondary);
}
```

And this is the snippet I have written to counter the issue:
```css
body
.markdown-preview-view
.markdown-embed
.markdown-preview-view {
    border-left: none;
}
```
